### ISSUE TITLE
not installable under chicken 5.x

### ISSUE THREAD

**Issue by masukomi** [chicken-mobile/concurrent-native-callbacks#6]
[Instructions for the port to chicken 5 are here](https://wiki.call-cc.org/porting-c4-to-c5). 

I don't know what needs to be done after upgrading the metadata to have it show up in the eggs repository for 5.0

```shell
$ chicken-install concurrent-native-callbacks                                                         
Server error:

Error: [Server] no such extension or version
"concurrent-native-callbacks"
#f
Server error:

Error: [Server] no such extension or version
"concurrent-native-callbacks"
#f

Error: extension or version not found: "concurrent-native-callbacks"
```

**Comment by masukomi** [comment]
In order to have it show up under chicken-install (after porting) you have to send the URL of the
.release-info file to the chicken users mailing list.  One of of CHICKEN maintainers will add
it to the central repository.

**Comment by bunny351** [comment]
The egg should be available via chicken-install for CHICKEN 5 now, I've pushed an updated version. It seems to work fine on Linux/x86_64, but the tests crash currently for me on OpenBSD 6.4.

**Comment by masukomi** [comment]
installed fine on macOS 👍 
haven't tried using yet.
